{% set name = "calour" %}
{% set version = "2018.10.1" %}
{% set sha256 = "7daba019cccb348fb533a048dc4360a237e32ae04af5342cf628915284f04b91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/biocore/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<35]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - nose
    - setuptools
    - numpy
    - scipy
    - pandas
    - matplotlib >=2.0
    - scikit-learn
    - scikit-bio >=0.5.1
    - biom-format
    - statsmodels
    - ipython
    - ipywidgets
    - pyqt >5
    - docrep
test:
  imports:
    - calour
    - calour.Experiment

about:
  home: https://biocore.github.io/calour/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'exploratory and interactive microbiome analyses based on heatmaps'
  description: |
    Calour is a python package for processing, analysis and interactive
    exploration of microbiome (and other matrix form data),
    incorporating external databases.
  doc_url: https://biocore.github.io/calour/
  dev_url: https://github.com/biocore/calour

extra:
  recipe-maintainers:
    - RNAer
    - amnona
