package:
  name: mygene
  version: "3.1.0"

source:
  url: https://files.pythonhosted.org/packages/13/7c/2e222bba58e788855e777e431b5528d9e545901f9699dae386fe2478b80a/mygene-3.1.0.tar.gz
  sha256: 307305d83b5f9c0722dd8a78642d59c0d9d7742e60f548040819274a330d53af

build:
  number: 0
  noarch: python
  skip: False

requirements:
  host:
    - python
    - setuptools
    - requests >=2.3.0

  run:
    - python
    - requests >=2.3.0

test:
  imports:
    - mygene

about:
  home: https://github.com/suLab/mygene.py
  license: BSD License
  summary: 'Python Client for MyGene.Info services.'
  license_family: BSD
