package:
  name: lambda
  version: '1.0.3'

source:
  url: https://github.com/seqan/lambda/archive/lambda-v1.0.3.tar.gz
  sha256: 324f90dbc095c56792a77a002e64a98465a4853f74a141a1182e7a6f540545a2

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.0.0
    - seqan-library
  host:
    - zlib
    - bzip2
  run:
    - zlib
    - bzip2

test:
  commands:
    - lambda2 --help


about:
  home: http://seqan.github.io/lambda/
  license: AGPLv3
  summary: Lambda is a local aligner optimized for many query sequences and searches in protein space
